import type { AssessmentRecord } from '../types/assessment';

export const INITIAL_ASSESSMENTS: AssessmentRecord[] = [
  {
    id: 'CERT-2026-0891',
    lotId: 'LOT-NSK-401',
    farmerName: 'Ramesh Patel',
    mandi: 'Lasalgaon APMC, Nashik',
    variety: 'red',
    sampleSize: 50,
    timestamp: '2026-09-26T10:30:00Z',
    dateFormatted: '26 Sep 2026, 10:30 AM',
    inspectorName: 'Er. Sandeep Jadhav',
    totalCount: 50,
    defects: {
      healthy: 43,
      sprouted: 2,
      rotten: 1,
      damaged: 2,
      undersized: 2,
    },
    gradeAPercent: 86,
    gradeBPercent: 8,
    ursPercent: 6,
    qualityScore: 91,
    overallGrade: 'Grade A',
    storageVerdict: 'pass',
  },
  {
    id: 'CERT-2026-0892',
    lotId: 'LOT-BWB-108',
    farmerName: 'Subal Mondal',
    mandi: 'Memari Kisan Mandi, Burdwan',
    variety: 'red',
    sampleSize: 45,
    timestamp: '2026-09-26T11:45:00Z',
    dateFormatted: '26 Sep 2026, 11:45 AM',
    inspectorName: 'Amitava Roy',
    totalCount: 45,
    defects: {
      healthy: 32,
      sprouted: 5,
      rotten: 2,
      damaged: 3,
      undersized: 3,
    },
    gradeAPercent: 71,
    gradeBPercent: 18,
    ursPercent: 11,
    qualityScore: 78,
    overallGrade: 'Grade B',
    storageVerdict: 'pass',
  },
  {
    id: 'CERT-2026-0893',
    lotId: 'LOT-IDR-722',
    farmerName: 'Kailash Chouhan',
    mandi: 'Chhawani Mandi, Indore',
    variety: 'red',
    sampleSize: 48,
    timestamp: '2026-09-25T16:15:00Z',
    dateFormatted: '25 Sep 2026, 04:15 PM',
    inspectorName: 'Sanjay Verma',
    totalCount: 48,
    defects: {
      healthy: 18,
      sprouted: 14,
      rotten: 9,
      damaged: 4,
      undersized: 3,
    },
    gradeAPercent: 38,
    gradeBPercent: 14,
    ursPercent: 48,
    qualityScore: 42,
    overallGrade: 'URS',
    storageVerdict: 'fail',
  },
];
